version: '3.1'

services: 
  blog_strap_api:
    container_name: blog_strapi_api
    hostname: blog_stripe_api
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: blog-strap-1
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - D:\dev\stripe\postgresdb\blog_strap_api:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432